---
name: Deploy Elementary Report
on:
  push:
    branches: [main, master]
  schedule:
    - cron: 00 22 * * 1-5
  workflow_dispatch:
jobs:
  elementary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dbt project
        uses: actions/checkout@v6
      - name: Run Elementary
        uses: elementary-data/run-elementary-action@v1
        with:
          warehouse-type: bigquery
          profiles-yml: ${{ secrets.ELEMENTARY_PROFILES_YML }}
          edr-command: edr report --file-path "report.html" --exclude-elementary-models
            "true" --days-back 90 && edr send-report --google-service-account-path
            "/tmp/gcs_keyfile.json" --gcs-bucket-name "${{ secrets.GCS_BUCKET_NAME }}"
            --update-bucket-website "true" --days-back 90
          bigquery-keyfile: ${{ secrets.ELEMENTARY_GCS_BIGQUERY_SA }}
          gcs-keyfile: ${{ secrets.ELEMENTARY_GCS_BIGQUERY_SA }}
      - name: Upload report
        uses: actions/upload-artifact@v6
        with:
          name: report.html
          path: report.html
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: edr.log
          path: edr.log
